export interface Character {
  id: string;
  name: string;
  tagline: string;
  category: "ai" | "developer" | "productivity" | "os_hardware" | "media_consumer";
  categoryLabel: string;
  launchYear: number;
  decade: "pre2010" | "2010s" | "2020s";
  primaryColor: "blue" | "red" | "green" | "yellow" | "multi";
  colorLabel: string;
  hasMascot: boolean;
  isDevTool: boolean;
  hasLetterG: boolean;
  iconName: string; // Lucide icon or GDG custom symbol
  badgeColor: string;
}

export const CHARACTERS: Character[] = [
  {
    id: "gemini",
    name: "Gemini",
    tagline: "Mô hình AI đa phương thức thế hệ mới của Google",
    category: "ai",
    categoryLabel: "Trí tuệ nhân tạo (AI)",
    launchYear: 2023,
    decade: "2020s",
    primaryColor: "blue",
    colorLabel: "Xanh dương",
    hasMascot: false,
    isDevTool: true,
    hasLetterG: true,
    iconName: "Sparkles",
    badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
  },
  {
    id: "chrome",
    name: "Google Chrome",
    tagline: "Trình duyệt web phổ biến nhất thế giới",
    category: "media_consumer",
    categoryLabel: "Người dùng phổ thông",
    launchYear: 2008,
    decade: "pre2010",
    primaryColor: "multi",
    colorLabel: "Đa sắc (4 màu Google)",
    hasMascot: true, // T-Rex dino
    isDevTool: true, // DevTools
    hasLetterG: false,
    iconName: "Globe",
    badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/30",
  },
  {
    id: "android",
    name: "Android",
    tagline: "Hệ điều hành di động mở hàng tỷ người dùng",
    category: "os_hardware",
    categoryLabel: "Hệ điều hành",
    launchYear: 2008,
    decade: "pre2010",
    primaryColor: "green",
    colorLabel: "Xanh lá",
    hasMascot: true, // Bugdroid
    isDevTool: true,
    hasLetterG: false,
    iconName: "Bot",
    badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/30",
  },
  {
    id: "youtube",
    name: "YouTube",
    tagline: "Nền tảng chia sẻ video trực tuyến số 1",
    category: "media_consumer",
    categoryLabel: "Đa phương tiện & Video",
    launchYear: 2005,
    decade: "pre2010",
    primaryColor: "red",
    colorLabel: "Đỏ",
    hasMascot: false,
    isDevTool: false,
    hasLetterG: false,
    iconName: "PlayCircle",
    badgeColor: "bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/30",
  },
  {
    id: "gmail",
    name: "Gmail",
    tagline: "Dịch vụ thư điện tử bảo mật và thông minh",
    category: "productivity",
    categoryLabel: "Ứng dụng làm việc",
    launchYear: 2004,
    decade: "pre2010",
    primaryColor: "red",
    colorLabel: "Đỏ / Đa sắc",
    hasMascot: false,
    isDevTool: false,
    hasLetterG: true,
    iconName: "Mail",
    badgeColor: "bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/30",
  },
  {
    id: "flutter",
    name: "Flutter",
    tagline: "UI Framework đa nền tảng từ một codebase duy nhất",
    category: "developer",
    categoryLabel: "Công cụ lập trình viên",
    launchYear: 2017,
    decade: "2010s",
    primaryColor: "blue",
    colorLabel: "Xanh dương",
    hasMascot: true, // Dash the bird
    isDevTool: true,
    hasLetterG: false,
    iconName: "Layers",
    badgeColor: "bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/30",
  },
  {
    id: "maps",
    name: "Google Maps",
    tagline: "Bản đồ định vị và chỉ đường toàn cầu",
    category: "productivity",
    categoryLabel: "Ứng dụng làm việc",
    launchYear: 2005,
    decade: "pre2010",
    primaryColor: "multi",
    colorLabel: "Đa sắc (4 màu Google)",
    hasMascot: false,
    isDevTool: false,
    hasLetterG: true,
    iconName: "MapPin",
    badgeColor: "bg-teal-500/10 text-teal-600 dark:text-teal-400 border-teal-500/30",
  },
  {
    id: "tensorflow",
    name: "TensorFlow",
    tagline: "Thư viện học máy & Deep Learning mã nguồn mở",
    category: "ai",
    categoryLabel: "Trí tuệ nhân tạo (AI)",
    launchYear: 2015,
    decade: "2010s",
    primaryColor: "yellow",
    colorLabel: "Cam / Vàng",
    hasMascot: false,
    isDevTool: true,
    hasLetterG: false,
    iconName: "BrainCircuit",
    badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/30",
  },
  {
    id: "drive",
    name: "Google Drive",
    tagline: "Lưu trữ đám mây an toàn và cộng tác thời gian thực",
    category: "productivity",
    categoryLabel: "Ứng dụng làm việc",
    launchYear: 2012,
    decade: "2010s",
    primaryColor: "multi",
    colorLabel: "Đa sắc (Vàng/Xanh)",
    hasMascot: false,
    isDevTool: false,
    hasLetterG: true,
    iconName: "HardDrive",
    badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
  },
  {
    id: "golang",
    name: "Go (Golang)",
    tagline: "Ngôn ngữ lập trình hiện đại, hiệu năng cao do Google thiết kế",
    category: "developer",
    categoryLabel: "Công cụ lập trình viên",
    launchYear: 2009,
    decade: "pre2010",
    primaryColor: "blue",
    colorLabel: "Xanh da trời (Cyan)",
    hasMascot: true, // Gopher
    isDevTool: true,
    hasLetterG: true,
    iconName: "Terminal",
    badgeColor: "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/30",
  },
  {
    id: "dino",
    name: "Chrome Dino",
    tagline: "Chú khủng long pixel sa mạc khi mất kết nối mạng",
    category: "media_consumer",
    categoryLabel: "Game & Linh vật",
    launchYear: 2014,
    decade: "2010s",
    primaryColor: "green",
    colorLabel: "Xám / Xanh",
    hasMascot: true,
    isDevTool: false,
    hasLetterG: false,
    iconName: "Footprints",
    badgeColor: "bg-stone-500/10 text-stone-600 dark:text-stone-400 border-stone-500/30",
  },
  {
    id: "google_cloud",
    name: "Google Cloud",
    tagline: "Hạ tầng điện toán đám mây và máy chủ toàn cầu",
    category: "developer",
    categoryLabel: "Công cụ lập trình viên",
    launchYear: 2008,
    decade: "pre2010",
    primaryColor: "blue",
    colorLabel: "Xanh dương",
    hasMascot: false,
    isDevTool: true,
    hasLetterG: true,
    iconName: "Cloud",
    badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
  },
  {
    id: "pixel",
    name: "Google Pixel",
    tagline: "Dòng điện thoại thông minh chụp ảnh AI đỉnh cao",
    category: "os_hardware",
    categoryLabel: "Phần cứng & Thiết bị",
    launchYear: 2016,
    decade: "2010s",
    primaryColor: "multi",
    colorLabel: "Đa sắc",
    hasMascot: false,
    isDevTool: false,
    hasLetterG: true,
    iconName: "Smartphone",
    badgeColor: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/30",
  },
  {
    id: "translate",
    name: "Google Dịch",
    tagline: "Cầu nối ngôn ngữ tức thì giữa hàng trăm thứ tiếng",
    category: "ai",
    categoryLabel: "Trí tuệ nhân tạo (AI)",
    launchYear: 2006,
    decade: "pre2010",
    primaryColor: "blue",
    colorLabel: "Xanh dương",
    hasMascot: false,
    isDevTool: false,
    hasLetterG: true,
    iconName: "Languages",
    badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
  },
  {
    id: "photos",
    name: "Google Photos",
    tagline: "Kho lưu giữ và tìm kiếm ảnh kỷ niệm bằng nhận diện AI",
    category: "media_consumer",
    categoryLabel: "Đa phương tiện & Video",
    launchYear: 2015,
    decade: "2010s",
    primaryColor: "multi",
    colorLabel: "Đa sắc (Chong chóng 4 màu)",
    hasMascot: false,
    isDevTool: false,
    hasLetterG: false,
    iconName: "Image",
    badgeColor: "bg-yellow-500/10 text-yellow-600 dark:text-yellow-400 border-yellow-500/30",
  },
  {
    id: "gdg",
    name: "GDG on Campus",
    tagline: "Cộng đồng sinh viên đam mê công nghệ Google",
    category: "developer",
    categoryLabel: "Cộng đồng & Đào tạo",
    launchYear: 2021,
    decade: "2020s",
    primaryColor: "multi",
    colorLabel: "Đa sắc (4 màu GDG)",
    hasMascot: false,
    isDevTool: true,
    hasLetterG: true,
    iconName: "Users2",
    badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/30",
  },
];
