export type CharacterTier = "consumer" | "developer" | "boss";

export interface Character {
  id: string;
  name: string;
  tagline: string;
  techLore?: string; // Special easter-egg lore for tech people and boss cards
  tier: CharacterTier;
  tierLabel: string;
  badgeStyle: string;

  // Deduction Matrix Attributes
  category: "search_info" | "media_video" | "productivity_workspace" | "os_hardware" | "cloud_dev" | "ai_deeptech";
  categoryLabel: string;

  // Target & Audience
  isConsumer: boolean;
  isDeveloper: boolean;
  isBoss: boolean;

  // Open Source & AI
  isOpenSource: boolean;
  isCoreAI: boolean;

  // Visual & Branding
  primaryColor: "blue" | "red" | "green" | "yellow_orange" | "multi";
  colorLabel: string;
  hasMascot: boolean;
  hasLetterG: boolean;

  // Timeline
  launchYear: number;
  era: "pioneer" | "growth" | "modern"; // pioneer (<2008), growth (2008-2016), modern (>=2017)
  eraLabel: string;

  // Specific Features
  isWorkspaceApp: boolean; // Gmail, Drive, Docs, Calendar, Meet
  hasHardware: boolean;    // Pixel
}

export const CHARACTERS: Character[] = [
  // ==========================================
  // 15 FAMILIAR GOOGLE PRODUCTS / SERVICES
  // ==========================================
  {
    id: "search",
    name: "Google Tìm Kiếm",
    tagline: "Cỗ máy tìm kiếm thông tin lớn nhất hành tinh",
    tier: "consumer",
    tierLabel: "Phổ thông",
    badgeStyle: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
    category: "search_info",
    categoryLabel: "Tìm kiếm & Thông tin",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "multi",
    colorLabel: "Đa sắc (4 màu Google)",
    hasMascot: false,
    hasLetterG: true,
    launchYear: 1998,
    era: "pioneer",
    eraLabel: "Thời kỳ đầu (< 2008)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "youtube",
    name: "YouTube",
    tagline: "Nền tảng chia sẻ và phát video trực tuyến số 1",
    tier: "consumer",
    tierLabel: "Phổ thông",
    badgeStyle: "bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/30",
    category: "media_video",
    categoryLabel: "Đa phương tiện & Video",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "red",
    colorLabel: "Đỏ",
    hasMascot: false,
    hasLetterG: false,
    launchYear: 2005,
    era: "pioneer",
    eraLabel: "Thời kỳ đầu (< 2008)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "gmail",
    name: "Gmail",
    tagline: "Dịch vụ thư điện tử bảo mật và thông minh",
    tier: "consumer",
    tierLabel: "Phổ thông",
    badgeStyle: "bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/30",
    category: "productivity_workspace",
    categoryLabel: "Google Workspace",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "red",
    colorLabel: "Đỏ / Đa sắc",
    hasMascot: false,
    hasLetterG: true,
    launchYear: 2004,
    era: "pioneer",
    eraLabel: "Thời kỳ đầu (< 2008)",
    isWorkspaceApp: true,
    hasHardware: false,
  },
  {
    id: "maps",
    name: "Google Maps",
    tagline: "Bản đồ định vị và chỉ đường vệ tinh toàn cầu",
    tier: "consumer",
    tierLabel: "Phổ thông",
    badgeStyle: "bg-teal-500/10 text-teal-600 dark:text-teal-400 border-teal-500/30",
    category: "search_info",
    categoryLabel: "Tìm kiếm & Thông tin",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "multi",
    colorLabel: "Đa sắc (4 màu Google)",
    hasMascot: false,
    hasLetterG: true,
    launchYear: 2005,
    era: "pioneer",
    eraLabel: "Thời kỳ đầu (< 2008)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "chrome",
    name: "Google Chrome",
    tagline: "Trình duyệt web phổ biến nhất thế giới (nhân Chromium)",
    tier: "consumer",
    tierLabel: "Phổ thông",
    badgeStyle: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/30",
    category: "search_info",
    categoryLabel: "Duyệt web & Internet",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: true, // Chromium
    isCoreAI: false,
    primaryColor: "multi",
    colorLabel: "Đa sắc (4 màu Google)",
    hasMascot: true, // T-Rex
    hasLetterG: false,
    launchYear: 2008,
    era: "growth",
    eraLabel: "Giai đoạn tăng trưởng (2008 - 2016)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "drive",
    name: "Google Drive",
    tagline: "Lưu trữ đám mây an toàn và đồng bộ dữ liệu thời gian thực",
    tier: "consumer",
    tierLabel: "Phổ thông",
    badgeStyle: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
    category: "productivity_workspace",
    categoryLabel: "Google Workspace",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "multi",
    colorLabel: "Đa sắc (Vàng / Xanh)",
    hasMascot: false,
    hasLetterG: true,
    launchYear: 2012,
    era: "growth",
    eraLabel: "Giai đoạn tăng trưởng (2008 - 2016)",
    isWorkspaceApp: true,
    hasHardware: false,
  },
  {
    id: "android",
    name: "Android",
    tagline: "Hệ điều hành di động mở phủ sóng hơn 3 tỷ thiết bị",
    tier: "consumer",
    tierLabel: "Hệ điều hành",
    badgeStyle: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/30",
    category: "os_hardware",
    categoryLabel: "Hệ điều hành & Nền tảng",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: true, // AOSP
    isCoreAI: false,
    primaryColor: "green",
    colorLabel: "Xanh lá",
    hasMascot: true, // Bugdroid
    hasLetterG: false,
    launchYear: 2008,
    era: "growth",
    eraLabel: "Giai đoạn tăng trưởng (2008 - 2016)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "photos",
    name: "Google Photos",
    tagline: "Kho lưu giữ và tìm kiếm ảnh kỷ niệm bằng nhận diện AI",
    tier: "consumer",
    tierLabel: "Phổ thông",
    badgeStyle: "bg-yellow-500/10 text-yellow-600 dark:text-yellow-400 border-yellow-500/30",
    category: "media_video",
    categoryLabel: "Đa phương tiện & Ảnh",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: true,
    primaryColor: "multi",
    colorLabel: "Đa sắc (Chong chóng 4 màu)",
    hasMascot: false,
    hasLetterG: false,
    launchYear: 2015,
    era: "growth",
    eraLabel: "Giai đoạn tăng trưởng (2008 - 2016)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "translate",
    name: "Google Dịch",
    tagline: "Cầu nối ngôn ngữ dịch thuật tự động giữa hơn 100 thứ tiếng",
    tier: "consumer",
    tierLabel: "Phổ thông",
    badgeStyle: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
    category: "ai_deeptech",
    categoryLabel: "Trí tuệ nhân tạo (AI)",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: true,
    primaryColor: "blue",
    colorLabel: "Xanh dương",
    hasMascot: false,
    hasLetterG: true,
    launchYear: 2006,
    era: "pioneer",
    eraLabel: "Thời kỳ đầu (< 2008)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "pixel",
    name: "Google Pixel",
    tagline: "Điện thoại thông minh phần cứng chụp ảnh AI đỉnh cao",
    tier: "consumer",
    tierLabel: "Phần cứng",
    badgeStyle: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border-indigo-500/30",
    category: "os_hardware",
    categoryLabel: "Thiết bị phần cứng",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "multi",
    colorLabel: "Đa sắc / Đen sang trọng",
    hasMascot: false,
    hasLetterG: true,
    launchYear: 2016,
    era: "growth",
    eraLabel: "Giai đoạn tăng trưởng (2008 - 2016)",
    isWorkspaceApp: false,
    hasHardware: true,
  },
  {
    id: "meet",
    name: "Google Meet",
    tagline: "Ứng dụng họp trực tuyến và hội thảo video an toàn",
    tier: "consumer",
    tierLabel: "Phổ thông",
    badgeStyle: "bg-green-500/10 text-green-600 dark:text-green-400 border-green-500/30",
    category: "productivity_workspace",
    categoryLabel: "Google Workspace",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "green",
    colorLabel: "Xanh lá / Đa sắc",
    hasMascot: false,
    hasLetterG: false,
    launchYear: 2017,
    era: "modern",
    eraLabel: "Thời kỳ hiện đại (>= 2017)",
    isWorkspaceApp: true,
    hasHardware: false,
  },
  {
    id: "play",
    name: "Google Play",
    tagline: "Cửa hàng ứng dụng, trò chơi và nội dung số của Android",
    tier: "consumer",
    tierLabel: "Phổ thông",
    badgeStyle: "bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/30",
    category: "search_info",
    categoryLabel: "Cửa hàng ứng dụng",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "multi",
    colorLabel: "Đa sắc (Tam giác 4 màu)",
    hasMascot: false,
    hasLetterG: true,
    launchYear: 2012,
    era: "growth",
    eraLabel: "Giai đoạn tăng trưởng (2008 - 2016)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "docs",
    name: "Google Docs",
    tagline: "Trình soạn thảo văn bản trực tuyến và cộng tác nhóm thời gian thực",
    tier: "consumer",
    tierLabel: "Phổ thông",
    badgeStyle: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
    category: "productivity_workspace",
    categoryLabel: "Google Workspace",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "blue",
    colorLabel: "Xanh dương",
    hasMascot: false,
    hasLetterG: true,
    launchYear: 2006,
    era: "pioneer",
    eraLabel: "Thời kỳ đầu (< 2008)",
    isWorkspaceApp: true,
    hasHardware: false,
  },
  {
    id: "calendar",
    name: "Google Lịch",
    tagline: "Quản lý thời gian biểu, lịch hẹn và sự kiện cuộc sống",
    tier: "consumer",
    tierLabel: "Phổ thông",
    badgeStyle: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
    category: "productivity_workspace",
    categoryLabel: "Google Workspace",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "blue",
    colorLabel: "Xanh dương",
    hasMascot: false,
    hasLetterG: true,
    launchYear: 2006,
    era: "pioneer",
    eraLabel: "Thời kỳ đầu (< 2008)",
    isWorkspaceApp: true,
    hasHardware: false,
  },
  {
    id: "dino",
    name: "Chrome Dino",
    tagline: "Chú khủng long pixel sa mạc khi mất kết nối mạng Internet",
    tier: "consumer",
    tierLabel: "Game & Linh vật",
    badgeStyle: "bg-stone-500/10 text-stone-600 dark:text-stone-400 border-stone-500/30",
    category: "media_video",
    categoryLabel: "Trò chơi & Linh vật",
    isConsumer: true,
    isDeveloper: false,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "green",
    colorLabel: "Xanh lá / Xám pixel",
    hasMascot: true,
    hasLetterG: false,
    launchYear: 2014,
    era: "growth",
    eraLabel: "Giai đoạn tăng trưởng (2008 - 2016)",
    isWorkspaceApp: false,
    hasHardware: false,
  },

  // ==========================================
  // 6 GOOGLE DEVELOPER TECHNOLOGIES
  // ==========================================
  {
    id: "flutter",
    name: "Flutter",
    tagline: "UI Framework đa nền tảng mã nguồn mở từ một codebase duy nhất",
    techLore: "Sử dụng ngôn ngữ Dart, vẽ trực tiếp qua engine Skia/Impeller, mang lại 60-120fps trên iOS, Android và Web.",
    tier: "developer",
    tierLabel: "Lập trình viên",
    badgeStyle: "bg-sky-500/10 text-sky-600 dark:text-sky-400 border-sky-500/30",
    category: "cloud_dev",
    categoryLabel: "Công cụ lập trình viên",
    isConsumer: false,
    isDeveloper: true,
    isBoss: false,
    isOpenSource: true,
    isCoreAI: false,
    primaryColor: "blue",
    colorLabel: "Xanh dương (Cyan)",
    hasMascot: true, // Dash the bird
    hasLetterG: false,
    launchYear: 2017,
    era: "modern",
    eraLabel: "Thời kỳ hiện đại (>= 2017)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "golang",
    name: "Go (Golang)",
    tagline: "Ngôn ngữ lập trình hệ thống hiệu năng cao, concurrency siêu việt",
    techLore: "Do các huyền thoại Rob Pike, Ken Thompson và Robert Griesemer thiết kế tại Google với Goroutines danh tiếng.",
    tier: "developer",
    tierLabel: "Lập trình viên",
    badgeStyle: "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/30",
    category: "cloud_dev",
    categoryLabel: "Ngôn ngữ lập trình",
    isConsumer: false,
    isDeveloper: true,
    isBoss: false,
    isOpenSource: true,
    isCoreAI: false,
    primaryColor: "blue",
    colorLabel: "Xanh da trời (Cyan)",
    hasMascot: true, // Gopher
    hasLetterG: true,
    launchYear: 2009,
    era: "growth",
    eraLabel: "Giai đoạn tăng trưởng (2008 - 2016)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "firebase",
    name: "Firebase",
    tagline: "Nền tảng Backend-as-a-Service, Realtime DB và Xác thực toàn diện",
    techLore: "Trợ thủ số 1 giúp lập trình viên mobile/web deploy backend chỉ trong vài dòng code mà không cần tự dựng server.",
    tier: "developer",
    tierLabel: "Lập trình viên",
    badgeStyle: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/30",
    category: "cloud_dev",
    categoryLabel: "Công cụ Backend & Cloud",
    isConsumer: false,
    isDeveloper: true,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "yellow_orange",
    colorLabel: "Cam / Vàng",
    hasMascot: false,
    hasLetterG: false,
    launchYear: 2011,
    era: "growth",
    eraLabel: "Giai đoạn tăng trưởng (2008 - 2016)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "tensorflow",
    name: "TensorFlow",
    tagline: "Thư viện học máy & Deep Learning mã nguồn mở hàng đầu thế giới",
    techLore: "Được xây dựng bởi nhóm Google Brain nhằm thương mại hóa mạng nơ-ron tích chập và tính toán ma trận Tensors.",
    tier: "developer",
    tierLabel: "Lập trình viên",
    badgeStyle: "bg-orange-500/10 text-orange-600 dark:text-orange-400 border-orange-500/30",
    category: "ai_deeptech",
    categoryLabel: "Trí tuệ nhân tạo (AI)",
    isConsumer: false,
    isDeveloper: true,
    isBoss: false,
    isOpenSource: true,
    isCoreAI: true,
    primaryColor: "yellow_orange",
    colorLabel: "Cam / Hổ phách",
    hasMascot: false,
    hasLetterG: false,
    launchYear: 2015,
    era: "growth",
    eraLabel: "Giai đoạn tăng trưởng (2008 - 2016)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "google_cloud",
    name: "Google Cloud (GCP)",
    tagline: "Hạ tầng điện toán đám mây, Big Data và AI clusters quy mô hành tinh",
    techLore: "Nơi vận hành BigQuery, Compute Engine và mạng cáp quang biển riêng trải dài khắp 5 châu lục của Google.",
    tier: "developer",
    tierLabel: "Lập trình viên",
    badgeStyle: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30",
    category: "cloud_dev",
    categoryLabel: "Hạ tầng Đám mây",
    isConsumer: false,
    isDeveloper: true,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "blue",
    colorLabel: "Xanh dương",
    hasMascot: false,
    hasLetterG: true,
    launchYear: 2008,
    era: "growth",
    eraLabel: "Giai đoạn tăng trưởng (2008 - 2016)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "gdg",
    name: "GDG on Campus",
    tagline: "Cộng đồng sinh viên đam mê công nghệ và sáng tạo giải pháp Google",
    techLore: "Mạng lưới câu lạc bộ sinh viên công nghệ toàn cầu, tổ chức Solution Challenge và các workshop lập trình chuyên sâu.",
    tier: "developer",
    tierLabel: "Cộng đồng Dev",
    badgeStyle: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/30",
    category: "cloud_dev",
    categoryLabel: "Cộng đồng & Đào tạo",
    isConsumer: false,
    isDeveloper: true,
    isBoss: false,
    isOpenSource: false,
    isCoreAI: false,
    primaryColor: "multi",
    colorLabel: "Đa sắc (4 màu Google)",
    hasMascot: false,
    hasLetterG: true,
    launchYear: 2021,
    era: "modern",
    eraLabel: "Thời kỳ hiện đại (>= 2017)",
    isWorkspaceApp: false,
    hasHardware: false,
  },

  // ==========================================
  // 3 "BOSS" CARDS CHO TECH PEOPLE
  // ==========================================
  {
    id: "kubernetes",
    name: "Kubernetes (K8s)",
    tagline: "Hệ điều hành đám mây thế giới (Khởi nguồn từ dự án bí mật Borg của Google)",
    techLore: "Trước khi mã nguồn mở năm 2014, hệ thống Borg nội bộ đã điều phối hàng tỷ containers mỗi tuần cho Google Search và Gmail. K8s đã trở thành chuẩn mực tuyệt đối của kỷ nguyên Cloud Native.",
    tier: "boss",
    tierLabel: "BOSS • Huyền Thoại Hạ Tầng",
    badgeStyle: "bg-blue-600/15 text-blue-500 dark:text-blue-300 border-blue-500/50 shadow-sm ring-1 ring-blue-500/30",
    category: "cloud_dev",
    categoryLabel: "Điều phối Đám mây (Cloud Native)",
    isConsumer: false,
    isDeveloper: true,
    isBoss: true,
    isOpenSource: true,
    isCoreAI: false,
    primaryColor: "blue",
    colorLabel: "Xanh dương (Hải quân K8s)",
    hasMascot: false, // Bánh lái Helm
    hasLetterG: false,
    launchYear: 2014,
    era: "growth",
    eraLabel: "Giai đoạn tăng trưởng (2008 - 2016)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "transformer",
    name: "Transformer ('Attention')",
    tagline: "Kiến trúc nền tảng sinh ra ChatGPT, Gemini, Claude và kỷ nguyên Gen-AI",
    techLore: "Xuất bản năm 2017 trong bài báo kinh điển 'Attention Is All You Need' của 8 nhà nghiên cứu Google. Cơ chế Self-Attention đã xóa bỏ hoàn toàn giới hạn của RNN và khai sinh ra toàn bộ cuộc cách mạng LLM.",
    tier: "boss",
    tierLabel: "BOSS • Kỷ Nguyên Gen-AI",
    badgeStyle: "bg-purple-600/15 text-purple-600 dark:text-purple-300 border-purple-500/50 shadow-sm ring-1 ring-purple-500/30",
    category: "ai_deeptech",
    categoryLabel: "Kiến trúc Nền tảng AI",
    isConsumer: false,
    isDeveloper: true,
    isBoss: true,
    isOpenSource: true,
    isCoreAI: true,
    primaryColor: "yellow_orange",
    colorLabel: "Tím / Vàng (Attention Core)",
    hasMascot: false,
    hasLetterG: false,
    launchYear: 2017,
    era: "modern",
    eraLabel: "Thời kỳ hiện đại (>= 2017)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
  {
    id: "deepmind",
    name: "Google DeepMind (AlphaGo)",
    tagline: "Đỉnh cao AGI giải mã Cờ vây thế giới và bí ẩn sinh học với AlphaFold",
    techLore: "Tháng 3/2016 tại Seoul, AlphaGo làm chấn động nhân loại khi đánh bại huyền thoại Lee Sedol 4-1 với nước cờ 37 bất hủ. Sau đó, AlphaFold giải mã cấu trúc của gần như toàn bộ 200 triệu protein đã biết.",
    tier: "boss",
    tierLabel: "BOSS • Đỉnh Cao AGI",
    badgeStyle: "bg-emerald-600/15 text-emerald-600 dark:text-emerald-300 border-emerald-500/50 shadow-sm ring-1 ring-emerald-500/30",
    category: "ai_deeptech",
    categoryLabel: "Nghiên cứu Trí tuệ Nhân tạo (AGI)",
    isConsumer: false,
    isDeveloper: true,
    isBoss: true,
    isOpenSource: false,
    isCoreAI: true,
    primaryColor: "multi",
    colorLabel: "Đa sắc / Dark AGI",
    hasMascot: false,
    hasLetterG: true,
    launchYear: 2016,
    era: "growth",
    eraLabel: "Giai đoạn tăng trưởng (2008 - 2016)",
    isWorkspaceApp: false,
    hasHardware: false,
  },
];
